### ISSUE TITLE
Looking forward to add FizzBuzz (JS)

### ISSUE THREAD

**Issue by ahmadfaizan965** [Harshal0902/Hacktoberfest#16]
Thinking of contributing some javascript projects to this repo. Should i first update in README as its not listed there ?

**Comment by ahmadfaizan965** [comment]
PR created.

**Comment by Harshal0902** [comment]
The project listed in the README.md are just some suggestions, you don't need to add any new ideas

**Comment by ahmadfaizan965** [comment]
> The project listed in the README.md are just some suggestions, you don't need to add any new ideas

Its really good. I get the ideas from it. However FizzBuzz wasn't there so i added it. Hope that doesn't bother.

**Comment by ahmadfaizan965** [comment]
i am working on some landing page (single page website). hopefully will push tomorrow.
