### ISSUE TITLE
Javascript Guess the number game

### ISSUE THREAD

**Issue by jeetsdev** [Harshal0902/Hacktoberfest#9]
I want to contribute to this project here, Can you let me know the format of the README.md file, or do I have to upload all the relevant files here...! @Harshal0902 @adityamittl

**Comment by Harshal0902** [comment]
@jeetsdev you have created a folder ```JavaScript``` and make a folder with name ```Guess the number game``` and put all the files there, and there is no need to create a separate README.md file for now.

**Comment by jeetsdev** [comment]
Got it. Gonna do it now.
